### ISSUE TITLE
GUI Remap searching doesnt work

### ISSUE THREAD

**Issue by refringe** [sp-tarkov/assembly-tool#9]
to fix:
![image](https://dev.sp-tarkov.com/attachments/397d26ad-aabf-4023-8cea-847aeb4ab616)

---
[Originally written](https://dev.sp-tarkov.com/SPT/AssemblyTool/issues/2) by _**CWX**_

**Comment by CJ-SPT** [comment]
This issue was previously closed on Gitea, closing.
